version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      DB_HOST: db   # 這裡已經修改為 'db'
      DB_USER: root   # 使用 root 用戶
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chat_app
    volumes:
      - ./migrations:/app/migrations
      - mysql_data:/var/lib/mysql 
    networks:
      - backend-network  # 確保 db 也在 backend-network 網路中

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    networks:
      - backend-network

  server:
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    networks:
      - backend-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - client
      - server
      - phpmyadmin
    networks:
      - frontend-network
      - backend-network

networks:
  backend-network:
    driver: bridge

  frontend-network:
    driver: bridge

volumes:
  db_data: {}
  mysql_data: {}
